// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dogTor.Models;

public partial class DetalleAtencion
{
    public int CodDetalle { get; set; }

    public int CodAtencion { get; set; }

    public int CodTipoA { get; set; }

    public string Observaciones { get; set; }

    public virtual Atencion CodAtencionNavigation { get; set; }

    public virtual TipoAtencion CodTipoANavigation { get; set; }
}