// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace dogTor.Models;

public partial class dogtorContext : DbContext
{
    public dogtorContext(DbContextOptions<dogtorContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Atencion> Atencions { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Disponibilidad> Disponibilidads { get; set; }

    public virtual DbSet<Mascotum> Mascota { get; set; }

    public virtual DbSet<TipoAtencion> TipoAtencions { get; set; }

    public virtual DbSet<TipoMascotum> TipoMascota { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Atencion>(entity =>
        {
            entity.HasKey(e => e.CodAtencion).HasName("PK__ATENCION__6AC5F2D056AFB299");

            entity.ToTable("ATENCION");

            entity.Property(e => e.CodAtencion).HasColumnName("cod_atencion");
            entity.Property(e => e.CodDisponibilidad).HasColumnName("cod_disponibilidad");
            entity.Property(e => e.CodMascota).HasColumnName("cod_mascota");
            entity.Property(e => e.CodTipoA).HasColumnName("cod_tipoA");
            entity.Property(e => e.Importe)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("importe");

            entity.HasOne(d => d.CodDisponibilidadNavigation).WithMany(p => p.Atencions)
                .HasForeignKey(d => d.CodDisponibilidad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ATENCION__cod_di__440B1D61");

            entity.HasOne(d => d.CodMascotaNavigation).WithMany(p => p.Atencions)
                .HasForeignKey(d => d.CodMascota)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ATENCION__cod_ma__44FF419A");

            entity.HasOne(d => d.CodTipoANavigation).WithMany(p => p.Atencions)
                .HasForeignKey(d => d.CodTipoA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ATENCION__cod_ti__45F365D3");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.CodCliente).HasName("PK__CLIENTE__08ED61F3781D2B1B");

            entity.ToTable("CLIENTE");

            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.Dni).HasColumnName("dni");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.Telefono)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("telefono");
        });

        modelBuilder.Entity<Disponibilidad>(entity =>
        {
            entity.HasKey(e => e.CodDisponibilidad).HasName("PK__DISPONIB__2B79026964A32769");

            entity.ToTable("DISPONIBILIDAD");

            entity.HasIndex(e => new { e.Fecha, e.Hora }, "UQ__DISPONIB__56E71B4F39FCA002").IsUnique();

            entity.Property(e => e.CodDisponibilidad).HasColumnName("cod_disponibilidad");
            entity.Property(e => e.Fecha)
                .HasColumnType("datetime")
                .HasColumnName("fecha");
            entity.Property(e => e.Hora).HasColumnName("hora");
            entity.Property(e => e.Ocupada).HasColumnName("ocupada");
        });

        modelBuilder.Entity<Mascotum>(entity =>
        {
            entity.HasKey(e => e.CodMascota).HasName("PK__MASCOTA__6BC4D21DDAF4F76F");

            entity.ToTable("MASCOTA");

            entity.Property(e => e.CodMascota).HasColumnName("cod_mascota");
            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.CodTipo).HasColumnName("cod_tipo");
            entity.Property(e => e.Edad).HasColumnName("edad");
            entity.Property(e => e.Eliminado)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MASCOTA_eliminado")
                .HasColumnName("eliminado");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");

            entity.HasOne(d => d.CodClienteNavigation).WithMany(p => p.Mascota)
                .HasForeignKey(d => d.CodCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MASCOTA__cod_cli__46E78A0C");

            entity.HasOne(d => d.CodTipoNavigation).WithMany(p => p.Mascota)
                .HasForeignKey(d => d.CodTipo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MASCOTA__cod_tip__47DBAE45");
        });

        modelBuilder.Entity<TipoAtencion>(entity =>
        {
            entity.HasKey(e => e.CodTipoA).HasName("PK__TIPO_ATE__A85295C94EE2C645");

            entity.ToTable("TIPO_ATENCION");

            entity.Property(e => e.CodTipoA).HasColumnName("cod_tipoA");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<TipoMascotum>(entity =>
        {
            entity.HasKey(e => e.CodTipo).HasName("PK__TIPO_MAS__7C06900DCED20727");

            entity.ToTable("TIPO_MASCOTA");

            entity.Property(e => e.CodTipo).HasColumnName("cod_tipo");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}