// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dogTor.Models;

public partial class TipoMascotum
{
    public int CodTipo { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Mascotum> Mascota { get; set; } = new List<Mascotum>();
}