// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dogTor.Models;

public partial class Mascotum
{
    public int CodMascota { get; set; }

    public string Nombre { get; set; }

    public int Edad { get; set; }

    public int CodCliente { get; set; }

    public int CodTipo { get; set; }

    public bool Eliminado { get; set; }

    public string ImagenMascota { get; set; }

    public virtual ICollection<Atencion> Atencions { get; set; } = new List<Atencion>();

    public virtual Cliente CodClienteNavigation { get; set; }

    public virtual TipoMascotum CodTipoNavigation { get; set; }
}