// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace dogTor.Models;

public partial class veterinariaContext : DbContext
{
    public veterinariaContext(DbContextOptions<veterinariaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Atencion> Atencions { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<DetalleAtencion> DetalleAtencions { get; set; }

    public virtual DbSet<Disponibilidad> Disponibilidads { get; set; }

    public virtual DbSet<EstadoAtencion> EstadoAtencions { get; set; }

    public virtual DbSet<Mascotum> Mascota { get; set; }

    public virtual DbSet<TipoAtencion> TipoAtencions { get; set; }

    public virtual DbSet<TipoMascotum> TipoMascota { get; set; }

    public virtual DbSet<Veterinario> Veterinario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Atencion>(entity =>
        {
            entity.HasKey(e => e.CodAtencion).HasName("PK__ATENCION__6AC5F2D0619A498A");

            entity.ToTable("ATENCION");

            entity.Property(e => e.CodAtencion).HasColumnName("cod_atencion");
            entity.Property(e => e.CodDisponibilidad).HasColumnName("cod_disponibilidad");
            entity.Property(e => e.CodMascota).HasColumnName("cod_mascota");
            entity.Property(e => e.CodTipoA).HasColumnName("cod_tipoA");
            entity.Property(e => e.CodVeterinario).HasColumnName("cod_veterinario");
            entity.Property(e => e.Importe)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("importe");

            entity.HasOne(d => d.CodDisponibilidadNavigation).WithMany(p => p.Atencions)
                .HasForeignKey(d => d.CodDisponibilidad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ATENCION_DISPONIBILIDAD");

            entity.HasOne(d => d.CodMascotaNavigation).WithMany(p => p.Atencions)
                .HasForeignKey(d => d.CodMascota)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ATENCION__cod_ma__4D94879B");

            entity.HasOne(d => d.CodTipoANavigation).WithMany(p => p.Atencions)
                .HasForeignKey(d => d.CodTipoA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ATENCION__cod_ti__4E88ABD4");

            entity.HasOne(d => d.CodVeterinarioNavigation).WithMany(p => p.Atencions)
                .HasForeignKey(d => d.CodVeterinario)
                .HasConstraintName("FK__ATENCION__cod_ve__4F7CD00D");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.CodCliente).HasName("PK__CLIENTE__08ED61F35B43F331");

            entity.ToTable("CLIENTE");

            entity.HasIndex(e => e.Dni, "UQ__CLIENTE__D87608A7E205546F").IsUnique();

            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.Dni).HasColumnName("dni");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.Telefono)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("telefono");
        });

        modelBuilder.Entity<DetalleAtencion>(entity =>
        {
            entity.HasKey(e => e.CodDetalle).HasName("PK__DETALLE___03E666AE4241F102");

            entity.ToTable("DETALLE_ATENCION");

            entity.Property(e => e.CodDetalle).HasColumnName("cod_detalle");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.CodAtencion).HasColumnName("cod_atencion");
            entity.Property(e => e.CodTipoA).HasColumnName("cod_tipoA");
            entity.Property(e => e.Observaciones)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("observaciones");
            entity.Property(e => e.PrecioUnitario)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio_unitario");

            entity.HasOne(d => d.CodAtencionNavigation).WithMany(p => p.DetalleAtencions)
                .HasForeignKey(d => d.CodAtencion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DETALLE_A__cod_a__5070F446");

            entity.HasOne(d => d.CodTipoANavigation).WithMany(p => p.DetalleAtencions)
                .HasForeignKey(d => d.CodTipoA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DETALLE_A__cod_t__5165187F");
        });

        modelBuilder.Entity<Disponibilidad>(entity =>
        {
            entity.HasKey(e => e.CodDisponibilidad).HasName("PK__DISPONIB__2B790269D824CC35");

            entity.ToTable("DISPONIBILIDAD");

            entity.Property(e => e.CodDisponibilidad).HasColumnName("cod_disponibilidad");
            entity.Property(e => e.CodEstado).HasColumnName("cod_estado");
            entity.Property(e => e.Fecha)
                .HasColumnType("datetime")
                .HasColumnName("fecha");
            entity.Property(e => e.Hora).HasColumnName("hora");

            entity.HasOne(d => d.CodEstadoNavigation).WithMany(p => p.Disponibilidads)
                .HasForeignKey(d => d.CodEstado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DISPONIBI__cod_e__49C3F6B7");
        });

        modelBuilder.Entity<EstadoAtencion>(entity =>
        {
            entity.HasKey(e => e.CodEstado).HasName("PK__ESTADO_A__D37A6AC51B92D080");

            entity.ToTable("ESTADO_ATENCION");

            entity.Property(e => e.CodEstado).HasColumnName("cod_estado");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Mascotum>(entity =>
        {
            entity.HasKey(e => e.CodMascota).HasName("PK__MASCOTA__6BC4D21D40002BC5");

            entity.ToTable("MASCOTA");

            entity.Property(e => e.CodMascota).HasColumnName("cod_mascota");
            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.CodTipo).HasColumnName("cod_tipo");
            entity.Property(e => e.Edad).HasColumnName("edad");
            entity.Property(e => e.Eliminado)
                .HasDefaultValue(true)
                .HasColumnName("eliminado");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");

            entity.HasOne(d => d.CodClienteNavigation).WithMany(p => p.Mascota)
                .HasForeignKey(d => d.CodCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MASCOTA__cod_cli__4AB81AF0");

            entity.HasOne(d => d.CodTipoNavigation).WithMany(p => p.Mascota)
                .HasForeignKey(d => d.CodTipo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MASCOTA__cod_tip__4BAC3F29");
        });

        modelBuilder.Entity<TipoAtencion>(entity =>
        {
            entity.HasKey(e => e.CodTipoA).HasName("PK__TIPO_ATE__A85295C98F53FC1E");

            entity.ToTable("TIPO_ATENCION");

            entity.Property(e => e.CodTipoA).HasColumnName("cod_tipoA");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.PrecioBase)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio_base");
        });

        modelBuilder.Entity<TipoMascotum>(entity =>
        {
            entity.HasKey(e => e.CodTipo).HasName("PK__TIPO_MAS__7C06900D4DA18949");

            entity.ToTable("TIPO_MASCOTA");

            entity.Property(e => e.CodTipo).HasColumnName("cod_tipo");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Veterinario>(entity =>
        {
            entity.HasKey(e => e.CodVeterinario).HasName("PK__VETERINA__58528A853FB71A0C");

            entity.ToTable("VETERINARIO");

            entity.HasIndex(e => e.Email, "UQ__VETERINA__AB6E6164090E9A36").IsUnique();

            entity.Property(e => e.CodVeterinario).HasColumnName("cod_veterinario");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Matricula)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("matricula");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("password");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}