// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dogTor.Models;

public partial class Veterinario
{
    public int CodVeterinario { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Matricula { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public virtual ICollection<Atencion> Atencions { get; set; } = new List<Atencion>();
}